//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutoEstoquesClient.ProdutoEstoquesServiceV2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/02", ConfigurationName="ProdutoEstoquesClient.ProdutoEstoquesServiceV2.IProdutoEstoquesServiceV2")]
    public interface IProdutoEstoquesServiceV2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/AdicionarEstoqueRespo" +
            "nse")]
        bool AdicionarEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/AdicionarEstoqueRespo" +
            "nse")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/RemoverEstoqueRespons" +
            "e")]
        bool RemoverEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/RemoverEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/ConsultarEstoqueRespo" +
            "nse")]
        int ConsultarEstoque(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutoEstoquesServiceV2/ConsultarEstoqueRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoEstoquesServiceV2Channel : ProdutoEstoquesClient.ProdutoEstoquesServiceV2.IProdutoEstoquesServiceV2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoEstoquesServiceV2Client : System.ServiceModel.ClientBase<ProdutoEstoquesClient.ProdutoEstoquesServiceV2.IProdutoEstoquesServiceV2>, ProdutoEstoquesClient.ProdutoEstoquesServiceV2.IProdutoEstoquesServiceV2
    {
        
        public ProdutoEstoquesServiceV2Client()
        {
        }
        
        public ProdutoEstoquesServiceV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProdutoEstoquesServiceV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutoEstoquesServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutoEstoquesServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AdicionarEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public bool RemoverEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public int ConsultarEstoque(string NumeroProduto)
        {
            return base.Channel.ConsultarEstoque(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProduto)
        {
            return base.Channel.ConsultarEstoqueAsync(NumeroProduto);
        }
    }
}
