//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutoEstoquesClient.ProdutoEstoquesService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ProdutoEstoques")]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescricaoProdutoField;
        
        private int EstoqueProdutoField;
        
        private string NomeProdutoField;
        
        private string NumeroProdutoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto
        {
            get
            {
                return this.DescricaoProdutoField;
            }
            set
            {
                this.DescricaoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstoqueProduto
        {
            get
            {
                return this.EstoqueProdutoField;
            }
            set
            {
                this.EstoqueProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto
        {
            get
            {
                return this.NomeProdutoField;
            }
            set
            {
                this.NomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProduto
        {
            get
            {
                return this.NumeroProdutoField;
            }
            set
            {
                this.NumeroProdutoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/01", ConfigurationName="ProdutoEstoquesClient.ProdutoEstoquesService.IProdutoEstoquesService")]
    public interface IProdutoEstoquesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ListarProdutosResponse")]
        string[] ListarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ListarProdutosResponse")]
        System.Threading.Tasks.Task<string[]> ListarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/IncluirProdutoResponse")]
        bool IncluirProduto(ProdutoEstoquesClient.ProdutoEstoquesService.Produto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/IncluirProdutoResponse")]
        System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutoEstoquesClient.ProdutoEstoquesService.Produto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverProdutoResponse")]
        bool RemoverProduto(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverProdutoResponse")]
        System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ConsultarEstoqueRespons" +
            "e")]
        int ConsultarEstoque(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/ConsultarEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/AdicionarEstoqueRespons" +
            "e")]
        bool AdicionarEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/AdicionarEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverEstoqueResponse")]
        bool RemoverEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/RemoverEstoqueResponse")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/VerProdutoResponse")]
        ProdutoEstoquesClient.ProdutoEstoquesService.Produto VerProduto(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutoEstoquesService/VerProdutoResponse")]
        System.Threading.Tasks.Task<ProdutoEstoquesClient.ProdutoEstoquesService.Produto> VerProdutoAsync(string NumeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoEstoquesServiceChannel : ProdutoEstoquesClient.ProdutoEstoquesService.IProdutoEstoquesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoEstoquesServiceClient : System.ServiceModel.ClientBase<ProdutoEstoquesClient.ProdutoEstoquesService.IProdutoEstoquesService>, ProdutoEstoquesClient.ProdutoEstoquesService.IProdutoEstoquesService
    {
        
        public ProdutoEstoquesServiceClient()
        {
        }
        
        public ProdutoEstoquesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProdutoEstoquesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutoEstoquesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutoEstoquesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string[] ListarProdutos()
        {
            return base.Channel.ListarProdutos();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarProdutosAsync()
        {
            return base.Channel.ListarProdutosAsync();
        }
        
        public bool IncluirProduto(ProdutoEstoquesClient.ProdutoEstoquesService.Produto Produto)
        {
            return base.Channel.IncluirProduto(Produto);
        }
        
        public System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutoEstoquesClient.ProdutoEstoquesService.Produto Produto)
        {
            return base.Channel.IncluirProdutoAsync(Produto);
        }
        
        public bool RemoverProduto(string NumeroProduto)
        {
            return base.Channel.RemoverProduto(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string NumeroProduto)
        {
            return base.Channel.RemoverProdutoAsync(NumeroProduto);
        }
        
        public int ConsultarEstoque(string NumeroProduto)
        {
            return base.Channel.ConsultarEstoque(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProduto)
        {
            return base.Channel.ConsultarEstoqueAsync(NumeroProduto);
        }
        
        public bool AdicionarEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public bool RemoverEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public ProdutoEstoquesClient.ProdutoEstoquesService.Produto VerProduto(string NumeroProduto)
        {
            return base.Channel.VerProduto(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<ProdutoEstoquesClient.ProdutoEstoquesService.Produto> VerProdutoAsync(string NumeroProduto)
        {
            return base.Channel.VerProdutoAsync(NumeroProduto);
        }
    }
}
